#!/usr/bin/env bash
# Displays information about subdomains.

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain")

        if [[ -n $result ]]; then
            record_type=$(dig "$sub.$domain" | awk '/^'${sub}'\./ {print $4}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        fi
    done
}

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

get_subdomain_info "$domain" "$subdomain"
