#!/usr/bin/env bash
# Update package lists

apt-get update

# Install nginx
apt-get install -y nginx

# Start nginx (not using systemctl)
/etc/init.d/nginx start

# Configure nginx to listen on port 80 and serve the "Hello World!" page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (not using systemctl)
/etc/init.d/nginx restart
