#!/usr/bin/env bash
# Update package lists and install Nginx

sudo apt-get update
sudo apt-get install nginx -y

# Configure Nginx default site
sudo sh -c "echo 'server {
    listen 80;
    server_name _;

    location / {
        return 200 \"Hello World!\";
    }

    location /redirect_me {
        return 301 https://example.com/new-page; # Replace with your desired redirection URL
    }

    error_page 404 /404.html;
    location = /404.html {
        return 404 \"Ceci n'est pas une page\";
    }
}' > /etc/nginx/sites-available/default"

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo nginx -s reload
