#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Update package lists and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Check if the haproxy.cfg file exists, if not create it
if [ ! -f "/etc/haproxy/haproxy.cfg" ]; then
    touch /etc/haproxy/haproxy.cfg
fi

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend skfada.tech
    bind 0:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 230171-web-01 54.90.50.81
    server 230171-web-02 100.25.191.152
EOF

# Restart HAProxy service
systemctl restart haproxy
