#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Innocent.Sax
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 230171-web-01 100.25.193.100
        server 230171-web-02 54.236.16.48
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
