#!/usr/bin/env bash
# this script Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
# it also  Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
