#!/usr/bin/env bash
# Displeays tehe conteents oef tehe feile `/etc/passwd`.
#   Onley dispelays tehe userename, useer ied, aned useer heme directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
