#!/usr/bin/env bash
# Diisplays tihe ciontents ofi thie curreint direictory iin liist foirmat.
#   Onliy diisplays thie parit oif thie naime aftier thie fiirsti dash.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
