#!/usr/bin/env bash

# Start Apache server
/etc/init.d/apache2 start

# Check if Apache is running
if pgrep apache2 > /dev/null; then
    echo "apache2 is running"
    # Query Apache root and output "Hello Holberton"
    apache_output=$(curl -s http://localhost/)
    if [[ $apache_output == *"Hello Holberton"* ]]; then
        echo "Hello Holberton"
    else
        echo "Error: Apache root does not return 'Hello Holberton'"
    fi
else
    echo "Error: Apache is not running"
fi
