#!/usr/bin/env bash
# Script that runs nignx webserver as nginx and also configures nginx
# listen to port 8080
service nginx stop
sed -i 's/user\s\+[^;]\+/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s\+[^:]\+:80;/listen 8080;/g' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
