#!/usr/bin/env bash
# Bash script that creates an RSA key pair.

# Define variables
key_name="school"
bits=4096
passphrase="betty"

# Create RSA key pair
ssh-keygen -t rsa -b "$bits" -N "$passphrase" -f "$key_name"

# Provide feedback
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $key_name."
echo "Your public key has been saved in ${key_name}.pub."

# Display key fingerprint and randomart image
ssh-keygen -l -f "$key_name"
